version: 2
jobs:
  node_server:
    working_directory: ~/auth0-android-sample
    docker:
      - image: circleci/node:8  
    steps:
      - checkout 
      - run:
          name: Setting up npm server
          command: npm init -y
      
      - run:
          name: Installing pip dependencies
          command: echo "Hi"
  # checkout:
  #   steps:
  #     - run: git clone https://github.com/benlizar/mobile-general scripts
  #     - persist_to_workspace:
  #       root: ~/
  #       path:
  #         - project
  #         - script
  android_00:
    working_directory: ~/auth0-android-sample/00-Login
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      - JVM_OPTS: -Xmx3200m
      - AUTH0_CONFIG: 00-Login/strings.xml.example
    steps:
      - checkout:
          path: ~/auth0-android-sample
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup Auth0 environment
          command: |
            mv $AUTH0_CONFIG.example $AUTH0_CONFIG
            sed -i 's/{CLIENT_ID}/'$client_id'/g' $AUTH0_CONFIG
            sed -i 's/{DOMAIN}/'$Domain'/g' $AUTH0_CONFIG
      # - attach_workspace: FOR FUTURE REFERENCES
      #     at: ~/auth0-android-sample
      - run:
          name: Chmod permissions 
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ./gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
workflows:
  version: 2
  node_android:
    jobs:
      - node_server
      - android_00:
          context: Quickstart MOBILE Test


